name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest app/tests/ --cov=app --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  build-and-push:
    name: Build and Push Docker Images
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/dash-app
            ghcr.io/${{ github.repository }}/airflow
          tags: |
            type=ref,event=branch
            type=sha,format=short

      - name: Build and push Dash app image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/dash/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/dash-app:latest
            ghcr.io/${{ github.repository }}/dash-app:${{ github.sha }}

      - name: Build and push Airflow image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/airflow/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/airflow:latest
            ghcr.io/${{ github.repository }}/airflow:${{ github.sha }}

  deploy:
    name: Deploy to AWS
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update ECS services
        run: |
          echo "Deployment to AWS would go here"
          echo "For example: aws ecs update-service --cluster marketing-dashboard --service dash-app --force-new-deployment"
        
        # For production:
        # run: |
        #   aws ecs update-service --cluster marketing-dashboard --service dash-app --force-new-deployment
        #   aws ecs update-service --cluster marketing-dashboard --service airflow-webserver --force-new-deployment
        #   aws ecs update-service --cluster marketing-dashboard --service airflow-scheduler --force-new-deployment 